import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";

const inter = PT_Sans({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Spice N Oil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
